name: Update Primary Lanes in Chungcheongnam, buk, Daejeon, Sejong

on:
  workflow_dispatch:
  schedule:
    - cron:  '38 18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Get the data and analyze
      run: |
        chmod +x ./scripts/umap_primary_lanes_Chungcheong.sh
        ./scripts/umap_primary_lanes_Chungcheong.sh
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push